### ISSUE TITLE
Allow users to upload own avatars in addition to already implemented Gravatar

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#10]
Add option to upload an avatar from their computer. After this, user can choose between this and Gravatar.

**Comment by erikaheidi** [comment]
I can work on this issue if its ok for you :)

**Comment by artur-gajewski** [comment]
Go for it, will assign it to you later today.

**Comment by erikaheidi** [comment]
Working on it!

I have some small questions: 
1) where should we save the user image files, and
2) shall we make the gravatar field (already there) editable by the user, in case he wants to add a different email for the gravatar?

I think we could write a Twig function to replace the currently used gravatar() , so we can check if the user has an uploaded image or not (if he doesnt, we try to show the gravatar for him which can be either the gravatar field or the email field, if the first one is empty).

I  made some changes already to the profile form: http://i.imgur.com/lJmqmWi.png

what do you think?

**Comment by artur-gajewski** [comment]
I like what you have done so far. Good idea on the twig extension, I was thinking about similar idea myself earlier.

The location of the uploads should be defined in parameters.yml file so that sysadmins can choose the location.

**Comment by erikaheidi** [comment]
Hello =) As you know, I've been working on this issue. I had some progress, mostly at the backend part, including changes to the profile editing form. I was able to make the image upload work fine, using form validation and such.

But I am having some difficulties with the Twig extension, I got something working but I'm not sure I'm in the right direction. 

Since it's taking too long, I think the best thing to do is PR to a separated branch (so you can get what I've done so far), so other people could help :)

**Comment by artur-gajewski** [comment]
Sure that is no problem and I thank you very very much for your
contribution!

Cheers,

Artur

2013/9/16 Erika Heidi notifications@github.com

**Comment by artur-gajewski** [comment]
@erikaheidi let me know when you push to a branch so that I can have a look at it.
